In [ ]:
import numpy as np

# Criar e preencher o mundo de Wumpus
def criar_mundo():
    rows, cols = 20,20
    wumpus_world = np.zeros((rows, cols), dtype=int)
    wumpus_world[0, 0] = 5  # Agente começa na posição (0, 0)

    # Colocar o ouro em uma posição aleatória diferente de (0, 0)
    gold_position = (np.random.randint(1, rows), np.random.randint(0, cols))
    wumpus_world[gold_position] = 1  # Ouro representado pelo valor 1

    return wumpus_world, gold_position


In [ ]:
def agent_mov(wumpus_world, current_pos, goal_pos):
    path = []
    while current_pos != goal_pos:
        if current_pos[0] < goal_pos[0]:
            current_pos = (current_pos[0] + 1, current_pos[1])
        elif current_pos[0] > goal_pos[0]:
            current_pos = (current_pos[0] - 1, current_pos[1])
        elif current_pos[1] < goal_pos[1]:
            current_pos = (current_pos[0], current_pos[1] + 1)
        elif current_pos[1] > goal_pos[1]:
            current_pos = (current_pos[0], current_pos[1] - 1)
        path.append(current_pos)
    return path



In [ ]:
def jogar_mundo_wumpus():
    wumpus_world, gold_position = criar_mundo()
    print("Mundo de Wumpus:")
    print(wumpus_world)

    current_pos = (0, 0)
    movements = []

    # procurar o ouro
    path_to_gold = agent_mov(wumpus_world, current_pos, gold_position)
    movements.extend(path_to_gold)
    score = len(path_to_gold)

    # voltar para (0, 0)
    path_to_home = agent_mov(wumpus_world, gold_position, (0, 0))
    movements.extend(path_to_home)
    score += len(path_to_home)

    print(f"Movimentos: {movements}")
    print(f"Pontuação Final: {score}")

    return score




In [ ]:
# Executa o jogo e salva os resultados
result = []
for _ in range(20):  # Executa 10 simulações
    final_score = jogar_mundo_wumpus()
    result.append(final_score)

print("Resultados:", result)

Mundo de Wumpus:
[[5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Movimentos: [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (2, 